import '../styles/globals.css';

import { ReactElement, ReactNode } from 'react';
import { NextPage } from 'next';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { SWRConfig } from 'swr';
import { AuthProvider, useAuth } from '../contexts/AuthContext';
import LoginModal from '../components/LoginModal';
import Header from '../components/Header';

type NextPageWithLayout = NextPage & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

function Layout({ Component, pageProps }: AppPropsWithLayout): ReactElement {
  const { isLoggedIn, shouldOpenLoginModal, closeLoginModal } = useAuth();

  const getLayout = Component.getLayout ?? ((page) => page);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="pt-16">{getLayout(<Component {...pageProps} />)}</div>

      {!isLoggedIn && (
        <LoginModal open={shouldOpenLoginModal} onClose={closeLoginModal} />
      )}
    </>
  );
}

function MyApp(props: AppPropsWithLayout): ReactElement {
  const swrConfig = {
    revalidateOnFocus: false,
    errorRetryCount: 3,
  };

  return (
    <SWRConfig value={swrConfig}>
      <AuthProvider>
        <Layout {...props} />
      </AuthProvider>
    </SWRConfig>
  );
}

export default MyApp;
