import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Feed from '../components/Feed'

export default function Home() {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Feed/>
    </div>
  )
}
